using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace GitBench.Localization.Generator;

[Generator]
public sealed class LocalizationGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor ParseError = new(
        id: "LOC001",
        title: "Localization catalog parse error",
        messageFormat: "Failed to parse '{0}': {1}",
        category: "Localization",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enFile = context.AdditionalTextsProvider
            .Where(static t => Normalize(t.Path).EndsWith("/localization/strings/en.json", StringComparison.Ordinal))
            .Select(static (t, ct) => (t.Path, Text: t.GetText(ct)?.ToString()));

        context.RegisterSourceOutput(enFile, static (spc, file) =>
        {
            if (string.IsNullOrWhiteSpace(file.Text))
                return;

            List<KeyValuePair<string, string>> entries;
            try
            {
                entries = MiniJson.ParseFlatObject(file.Text!);
            }
            catch (Exception ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(ParseError, Location.None, file.Path, ex.Message));
                return;
            }

            spc.AddSource("Strings.g.cs", SourceText.From(Emit(entries), Encoding.UTF8));
        });
    }

    private static string Normalize(string path) => path.Replace('\\', '/').ToLowerInvariant();

    private static string Emit(List<KeyValuePair<string, string>> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace GitBench.Localization;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class Strings");
        sb.AppendLine("{");

        foreach (var e in entries)
            sb.AppendLine($"    public required string {Identifier(e.Key)} {{ get; init; }}");

        sb.AppendLine();
        sb.AppendLine("    public static readonly Strings En = new()");
        sb.AppendLine("    {");
        foreach (var e in entries)
            sb.AppendLine($"        {Identifier(e.Key)} = \"{Escape(e.Value)}\",");
        sb.AppendLine("    };");

        sb.AppendLine();
        sb.AppendLine("    public static readonly Strings Pseudo = new()");
        sb.AppendLine("    {");
        foreach (var e in entries)
            sb.AppendLine($"        {Identifier(e.Key)} = \"{Escape(Pseudoize(e.Value))}\",");
        sb.AppendLine("    };");

        sb.AppendLine();
        sb.AppendLine("    public static Strings For(Locale locale) => locale switch");
        sb.AppendLine("    {");
        sb.AppendLine("        Locale.Pseudo => Pseudo,");
        sb.AppendLine("        _ => En,");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Identifier(string key)
    {
        var sb = new StringBuilder();
        var upper = true;
        foreach (var c in key)
        {
            if (c is '.' or '_' or '-' or ' ' or '/')
            {
                upper = true;
                continue;
            }

            if (sb.Length == 0 && !char.IsLetter(c) && c != '_')
                sb.Append('_');

            sb.Append(upper ? char.ToUpperInvariant(c) : c);
            upper = false;
        }

        return sb.Length == 0 ? "_" : sb.ToString();
    }

    private static string Escape(string s)
    {
        var sb = new StringBuilder(s.Length + 8);
        foreach (var c in s)
            sb.Append(c switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => c.ToString(),
            });
        return sb.ToString();
    }

    private static string Pseudoize(string s)
    {
        var sb = new StringBuilder(s.Length + 8);
        sb.Append('[');
        foreach (var c in s)
            sb.Append(Accent(c));

        var pad = Math.Max(1, s.Length / 3);
        sb.Append(' ');
        for (var i = 0; i < pad; i++)
            sb.Append('·');
        sb.Append(']');
        return sb.ToString();
    }

    private static char Accent(char c) => c switch
    {
        'a' => 'á', 'e' => 'é', 'i' => 'í', 'o' => 'ó', 'u' => 'ú',
        'A' => 'Á', 'E' => 'É', 'I' => 'Í', 'O' => 'Ó', 'U' => 'Ú',
        'c' => 'ç', 'C' => 'Ç', 'n' => 'ñ', 'N' => 'Ñ', 'y' => 'ý', 'Y' => 'Ý',
        _ => c,
    };
}
