"""Regenerates GitBench/Assets/Queries/Highlights/*.scm from the grammar submodules.

Syntax highlighting runs each grammar's own highlights.scm rather than a query we write, which is
what makes thirteen languages affordable. Those files live in the submodules under
external/cs_tree_sitter/native/vendor, so a pin bump can move them out from under us: this script
re-copies them and re-applies the handful of local edits, so the edits survive the bump instead of
being remembered.

Two languages are absent on purpose. Markdown and HTML highlight through *injections* -- a fenced
block's own language, a <script> body, and for Markdown a whole second grammar for its inline
syntax -- which the highlighter does not run. Shipping no query is what routes them to TextMate,
where they are better off. Adding a file here is the only thing needed to route a language.

Usage: python scripts/vendor-highlight-queries.py
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR = os.path.join(ROOT, "external", "cs_tree_sitter", "native", "vendor")
OUT = os.path.join(ROOT, "GitBench", "Assets", "Queries", "Highlights")

# Output name (the tree_sitter_<name> the bundled library exports) -> the repos whose queries make
# it up. TypeScript and TSX concatenate JavaScript's, the same way tree-sitter's own highlight
# configuration does: their own files hold only what JavaScript's does not.
SOURCES = {
    "c_sharp": ["tree-sitter-c-sharp"],
    "typescript": ["tree-sitter-javascript", "tree-sitter-typescript"],
    "tsx": ["tree-sitter-javascript", "tree-sitter-typescript"],
    "javascript": ["tree-sitter-javascript"],
    "json": ["tree-sitter-json"],
    "css": ["tree-sitter-css"],
    "yaml": ["tree-sitter-yaml"],
    "python": ["tree-sitter-python"],
    "go": ["tree-sitter-go"],
    "rust": ["tree-sitter-rust"],
    "java": ["tree-sitter-java"],
    "bash": ["tree-sitter-bash"],
    "c": ["tree-sitter-c"],
}

# Local edits, re-applied on every regeneration. A substitution that stops matching is an error
# rather than a silent no-op: that means upstream changed the text the edit was compensating for,
# and someone has to look at whether the edit is still needed.
SUBSTITUTIONS = {
    "rust": [(
        "(integer_literal) @constant.builtin\n(float_literal) @constant.builtin",
        "; LOCAL: upstream tags numeric literals @constant.builtin, where every other bundled\n"
        "; LOCAL: grammar tags them @number. Left alone, a Rust literal would be a different color\n"
        "; LOCAL: from the identical literal in the Go file beside it.\n"
        "(integer_literal) @number\n(float_literal) @number",
    )],
}

# Blocks moved to the front of a file. Capture precedence is "the later pattern wins", which is
# what twelve of the thirteen files are written for -- a broad pattern up top that the specific
# ones below it override. Go alone puts its broad patterns last, expecting the first match to win,
# so under one rule its function declarations would come out as plain variables. Moving that block
# to the front is the whole of the fix.
REORDERINGS = {
    "go": ["""; Identifiers

(type_identifier) @type
(field_identifier) @property
(identifier) @variable"""],
}

# Appended after the vendored text.
ADDITIONS = {
    "c_sharp": "; LOCAL: upstream only captures an invocation through a member access, so a bare\n"
               "; LOCAL: `Swap(a, b)` came back as @variable from the catch-all identifier pattern.\n"
               "(invocation_expression function: (identifier) @function)",
}

HEADER = """; Syntax highlighting captures, vendored from the grammar's own repository.
;
; Generated by scripts/vendor-highlight-queries.py -- edit that, not this. Local edits are marked
; `; LOCAL:`, and every `(#is-not? ...)` predicate is stripped (a tree-sitter-highlight crate
; feature this host does not implement; both uses sit beside a #match?/#eq? that already narrows).
;
; Capture order carries no priority here. The two upstream conventions disagree about whether the
; catch-all `(identifier) @variable` goes first or last, so TreeSitterSyntaxHighlighter breaks an
; exact tie on the color slot instead -- see the remarks on its Coalesce method.
;
; Source:
"""


def pin(repo):
    result = subprocess.run(
        ["git", "-C", os.path.join(VENDOR, repo), "rev-parse", "--short", "HEAD"],
        capture_output=True, text=True)
    return result.stdout.strip() or "unpinned"


def main():
    if not os.path.isdir(VENDOR):
        sys.exit(f"No grammar submodules at {VENDOR}. Run: git submodule update --init --recursive")

    os.makedirs(OUT, exist_ok=True)

    for name, repos in sorted(SOURCES.items()):
        sources, parts = [], []

        for repo in repos:
            path = os.path.join(VENDOR, repo, "queries", "highlights.scm")
            if not os.path.isfile(path):
                sys.exit(f"{name}: {repo} ships no queries/highlights.scm")

            text = re.sub(r"[ \t]*\(#is-not\?[^)]*\)", "", open(path, encoding="utf-8").read())
            sources.append(f";   {repo}/queries/highlights.scm @ {pin(repo)}")
            parts.append(text.strip())

        body = "\n\n".join(parts)

        for old, new in SUBSTITUTIONS.get(name, []):
            if old not in body:
                sys.exit(f"{name}: a local edit no longer matches upstream; review it:\n{old}")
            body = body.replace(old, new)

        for block in REORDERINGS.get(name, []):
            if block not in body:
                sys.exit(f"{name}: a reordered block no longer matches upstream; review it:\n{block}")
            moved = "; LOCAL: moved to the front so the specific patterns below override it.\n" + block
            body = moved + "\n\n" + body.replace(block, "").strip()

        if name in ADDITIONS:
            body += "\n\n" + ADDITIONS[name]

        with open(os.path.join(OUT, name + ".scm"), "w", encoding="utf-8", newline="\n") as f:
            f.write(HEADER + "\n".join(sources) + "\n\n" + body + "\n")

        print(f"{name}.scm <- {' + '.join(repos)}")


if __name__ == "__main__":
    main()
