import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR = os.path.join(ROOT, "external", "cs_tree_sitter", "native", "vendor")
OUT = os.path.join(ROOT, "GitBench", "Assets", "Queries", "Highlights")
INJECTIONS_OUT = os.path.join(ROOT, "GitBench", "Assets", "Queries", "Injections")

# Output name (the tree_sitter_<name> the bundled library exports) -> the checkouts whose queries
# make it up, written as the path under vendor/ holding the queries directory. TypeScript and TSX
# concatenate JavaScript's, the same way tree-sitter's own highlight configuration does: their own
# files hold only what JavaScript's does not.
SOURCES = {
    "c_sharp": ["tree-sitter-c-sharp"],
    "typescript": ["tree-sitter-javascript", "tree-sitter-typescript"],
    "tsx": ["tree-sitter-javascript", "tree-sitter-typescript"],
    "javascript": ["tree-sitter-javascript"],
    "json": ["tree-sitter-json"],
    "css": ["tree-sitter-css"],
    "html": ["tree-sitter-html"],
    "markdown": ["tree-sitter-markdown/tree-sitter-markdown"],
    "markdown_inline": ["tree-sitter-markdown/tree-sitter-markdown-inline"],
    "yaml": ["tree-sitter-yaml"],
    "python": ["tree-sitter-python"],
    "go": ["tree-sitter-go"],
    "rust": ["tree-sitter-rust"],
    "java": ["tree-sitter-java"],
    "bash": ["tree-sitter-bash"],
    "c": ["tree-sitter-c"],
    "toml": ["tree-sitter-toml"],
}

# The same, for injections.scm. Only the grammars that embed another language have one, and only
# the ones we want run are listed: an injection into a grammar we do not bundle costs nothing, but
# an injection we never wanted to follow would.
INJECTION_SOURCES = {
    "html": ["tree-sitter-html"],
    "markdown": ["tree-sitter-markdown/tree-sitter-markdown"],
    "markdown_inline": ["tree-sitter-markdown/tree-sitter-markdown-inline"],
}

# Local edits, re-applied on every regeneration. A substitution that stops matching is an error
# rather than a silent no-op: that means upstream changed the text the edit was compensating for,
# and someone has to look at whether the edit is still needed.
SUBSTITUTIONS = {
    "markdown_inline": [(
        """[
  (emphasis_delimiter)
  (code_span_delimiter)
] @punctuation.delimiter""",
        "; LOCAL: upstream paints the ** and the backticks as plain delimiters, which leaves a bold\n"
        "; LOCAL: run three colors wide. TextMate colors them with what they delimit, and a Markdown\n"
        "; LOCAL: file switching engines should not change appearance.\n"
        "(emphasis_delimiter) @text.emphasis\n"
        "(code_span_delimiter) @text.literal",
    )],
    "toml": [(
        """(pair
  (bare_key)) @property""",
        "; LOCAL: upstream hangs @property off the pair rather than off its key, so it paints\n"
        "; LOCAL: the whole `key = value` and then loses the key itself to the catch-all\n"
        "; LOCAL: `(bare_key) @type` above it, which this host resolves widest-span-first.\n"
        "; LOCAL: JSON and YAML both paint a mapping key @property, and a TOML key is no more\n"
        "; LOCAL: a type than those are.\n"
        "(pair\n  (bare_key) @property)",
    )],
    "rust": [(
        "(integer_literal) @constant.builtin\n(float_literal) @constant.builtin",
        "; LOCAL: upstream tags numeric literals @constant.builtin, where every other bundled\n"
        "; LOCAL: grammar tags them @number. Left alone, a Rust literal would be a different color\n"
        "; LOCAL: from the identical literal in the Go file beside it.\n"
        "(integer_literal) @number\n(float_literal) @number",
    )],
}

# Blocks moved to the front of a file. Capture precedence is "the later pattern wins", which is
# what twelve of the thirteen files are written for -- a broad pattern up top that the specific
# ones below it override. Go alone puts its broad patterns last, expecting the first match to win,
# so under one rule its function declarations would come out as plain variables. Moving that block
# to the front is the whole of the fix.
REORDERINGS = {
    "go": ["""; Identifiers

(type_identifier) @type
(field_identifier) @property
(identifier) @variable"""],
}

# Appended after the vendored text.
ADDITIONS = {
    "c_sharp": "; LOCAL: upstream only captures an invocation through a member access, so a bare\n"
               "; LOCAL: `Swap(a, b)` came back as @variable from the catch-all identifier pattern.\n"
               "(invocation_expression function: (identifier) @function)",
}

HEADER = """; Syntax highlighting captures, vendored from the grammar's own repository.
;
; Generated by scripts/vendor-highlight-queries.py -- edit that, not this. Local edits are marked
; `; LOCAL:`, and every `(#is-not? ...)` predicate is stripped (a tree-sitter-highlight crate
; feature this host does not implement; both uses sit beside a #match?/#eq? that already narrows).
;
; Capture order carries no priority here. The two upstream conventions disagree about whether the
; catch-all `(identifier) @variable` goes first or last, so TreeSitterSyntaxHighlighter breaks an
; exact tie on the color slot instead -- see the remarks on its Coalesce method.
;
; Source:
"""


INJECTION_HEADER = """; Injected languages, vendored from the grammar's own repository.
;
; Generated by scripts/vendor-highlight-queries.py -- edit that, not this.
;
; @injection.content is the region, and its language is either named by an @injection.language
; capture (a fenced block's info string) or set outright by the pattern. A language we bundle no
; grammar for leaves its region uncolored, which is why the ones naming latex and toml are kept.
;
; Source:
"""


def pin(source):
    result = subprocess.run(
        ["git", "-C", os.path.join(VENDOR, source.split("/")[0]), "rev-parse", "--short", "HEAD"],
        capture_output=True, text=True)
    return result.stdout.strip() or "unpinned"


def main():
    if not os.path.isdir(VENDOR):
        sys.exit(f"No grammar submodules at {VENDOR}. Run: git submodule update --init --recursive")

    os.makedirs(OUT, exist_ok=True)

    for name, repos in sorted(SOURCES.items()):
        sources, parts = [], []

        for repo in repos:
            path = os.path.join(VENDOR, *repo.split("/"), "queries", "highlights.scm")
            if not os.path.isfile(path):
                sys.exit(f"{name}: {repo} ships no queries/highlights.scm")

            text = re.sub(r"[ \t]*\(#is-not\?[^)]*\)", "", open(path, encoding="utf-8").read())
            sources.append(f";   {repo}/queries/highlights.scm @ {pin(repo)}")
            parts.append(text.strip())

        body = "\n\n".join(parts)

        for old, new in SUBSTITUTIONS.get(name, []):
            if old not in body:
                sys.exit(f"{name}: a local edit no longer matches upstream; review it:\n{old}")
            body = body.replace(old, new)

        for block in REORDERINGS.get(name, []):
            if block not in body:
                sys.exit(f"{name}: a reordered block no longer matches upstream; review it:\n{block}")
            moved = "; LOCAL: moved to the front so the specific patterns below override it.\n" + block
            body = moved + "\n\n" + body.replace(block, "").strip()

        if name in ADDITIONS:
            body += "\n\n" + ADDITIONS[name]

        with open(os.path.join(OUT, name + ".scm"), "w", encoding="utf-8", newline="\n") as f:
            f.write(HEADER + "\n".join(sources) + "\n\n" + body + "\n")

        print(f"{name}.scm <- {' + '.join(repos)}")

    os.makedirs(INJECTIONS_OUT, exist_ok=True)

    for name, repos in sorted(INJECTION_SOURCES.items()):
        sources, parts = [], []

        for repo in repos:
            path = os.path.join(VENDOR, *repo.split("/"), "queries", "injections.scm")
            if not os.path.isfile(path):
                sys.exit(f"{name}: {repo} ships no queries/injections.scm")

            sources.append(f";   {repo}/queries/injections.scm @ {pin(repo)}")
            parts.append(open(path, encoding="utf-8").read().strip())

        with open(os.path.join(INJECTIONS_OUT, name + ".scm"), "w", encoding="utf-8", newline="\n") as f:
            f.write(INJECTION_HEADER + "\n".join(sources) + "\n\n" + "\n\n".join(parts) + "\n")

        print(f"injections/{name}.scm <- {' + '.join(repos)}")


if __name__ == "__main__":
    main()
