namespace GitBench.Features.Diff;

/// <summary>
/// Maps a file path to the TextMate language id GitBench highlights it as, or null when the
/// language isn't supported (the diff then renders plain). This is the single place new
/// languages are registered: add one extension (or exact filename) → language-id row. The
/// returned id is the one TextMateSharp's <c>RegistryOptions.GetScopeByLanguageId</c>
/// understands.
/// </summary>
internal static class LanguageRegistry
{
    // Extension (with leading dot) → TextMateSharp language id, covering every grammar the
    // TextMateSharp.Grammars package bundles; each language's extensions come from that
    // package's own grammar manifest. Case-insensitive: paths from git keep their on-disk
    // casing, and ".CS" must highlight the same as ".cs". Dotfile names (".gitignore") also
    // resolve here because Path.GetExtension treats the whole name as the extension.
    private static readonly Dictionary<string, string> ByExtension = new(StringComparer.OrdinalIgnoreCase)
    {
        [".adoc"] = "asciidoc",
        [".bat"] = "bat",
        [".cmd"] = "bat",
        [".c"] = "c",
        [".i"] = "c",
        [".clj"] = "clojure",
        [".cljs"] = "clojure",
        [".cljc"] = "clojure",
        [".cljx"] = "clojure",
        [".clojure"] = "clojure",
        [".edn"] = "clojure",
        [".coffee"] = "coffeescript",
        [".cson"] = "coffeescript",
        [".iced"] = "coffeescript",
        [".cpp"] = "cpp",
        [".cc"] = "cpp",
        [".cxx"] = "cpp",
        [".c++"] = "cpp",
        [".hpp"] = "cpp",
        [".hh"] = "cpp",
        [".hxx"] = "cpp",
        [".h++"] = "cpp",
        [".h"] = "cpp",
        [".ii"] = "cpp",
        [".ino"] = "cpp",
        [".inl"] = "cpp",
        [".ipp"] = "cpp",
        [".ixx"] = "cpp",
        [".tpp"] = "cpp",
        [".txx"] = "cpp",
        [".cu"] = "cuda-cpp",
        [".cuh"] = "cuda-cpp",
        [".cs"] = "csharp",
        [".csx"] = "csharp",
        [".cake"] = "csharp",
        [".css"] = "css",
        [".dart"] = "dart",
        [".diff"] = "diff",
        [".patch"] = "diff",
        [".rej"] = "diff",
        [".dockerfile"] = "dockerfile",
        [".containerfile"] = "dockerfile",
        [".fs"] = "fsharp",
        [".fsi"] = "fsharp",
        [".fsx"] = "fsharp",
        [".fsscript"] = "fsharp",
        [".gitignore"] = "ignore",
        [".gitignore_global"] = "ignore",
        [".go"] = "go",
        [".groovy"] = "groovy",
        [".gvy"] = "groovy",
        [".gradle"] = "groovy",
        [".jenkinsfile"] = "groovy",
        [".nf"] = "groovy",
        [".handlebars"] = "handlebars",
        [".hbs"] = "handlebars",
        [".hjs"] = "handlebars",
        [".hlsl"] = "hlsl",
        [".hlsli"] = "hlsl",
        [".fx"] = "hlsl",
        [".fxh"] = "hlsl",
        [".vsh"] = "hlsl",
        [".psh"] = "hlsl",
        [".cginc"] = "hlsl",
        [".compute"] = "hlsl",
        [".html"] = "html",
        [".htm"] = "html",
        [".shtml"] = "html",
        [".xhtml"] = "html",
        [".xht"] = "html",
        [".mdoc"] = "html",
        [".jsp"] = "html",
        [".asp"] = "html",
        [".aspx"] = "html",
        [".jshtm"] = "html",
        [".volt"] = "html",
        [".ejs"] = "html",
        [".rhtml"] = "html",
        [".ini"] = "ini",
        [".properties"] = "properties",
        [".cfg"] = "properties",
        [".conf"] = "properties",
        [".directory"] = "properties",
        [".gitattributes"] = "properties",
        [".gitconfig"] = "properties",
        [".gitmodules"] = "properties",
        [".editorconfig"] = "properties",
        [".env"] = "properties",
        [".java"] = "java",
        [".jav"] = "java",
        [".js"] = "javascript",
        [".es6"] = "javascript",
        [".mjs"] = "javascript",
        [".cjs"] = "javascript",
        [".pac"] = "javascript",
        [".jsx"] = "javascriptreact",
        [".json"] = "json",
        [".bowerrc"] = "json",
        [".jscsrc"] = "json",
        [".webmanifest"] = "json",
        [".map"] = "json",
        [".har"] = "json",
        [".jslintrc"] = "json",
        [".jsonld"] = "json",
        [".geojson"] = "json",
        [".ipynb"] = "json",
        [".jsonc"] = "jsonc",
        [".eslintrc"] = "jsonc",
        [".jsfmtrc"] = "jsonc",
        [".jshintrc"] = "jsonc",
        [".swcrc"] = "jsonc",
        [".hintrc"] = "jsonc",
        [".babelrc"] = "jsonc",
        [".jl"] = "julia",
        [".sty"] = "tex",
        [".cls"] = "tex",
        [".bbx"] = "tex",
        [".cbx"] = "tex",
        [".tex"] = "latex",
        [".ltx"] = "latex",
        [".ctx"] = "latex",
        [".bib"] = "bibtex",
        [".less"] = "less",
        [".log"] = "log",
        [".lua"] = "lua",
        [".mak"] = "makefile",
        [".mk"] = "makefile",
        [".md"] = "markdown",
        [".mkd"] = "markdown",
        [".mdwn"] = "markdown",
        [".mdown"] = "markdown",
        [".markdown"] = "markdown",
        [".markdn"] = "markdown",
        [".mdtxt"] = "markdown",
        [".mdtext"] = "markdown",
        [".workbook"] = "markdown",
        [".m"] = "objective-c",
        [".mm"] = "objective-cpp",
        [".pas"] = "pascal",
        [".pp"] = "pascal",
        [".pl"] = "perl",
        [".pm"] = "perl",
        [".pod"] = "perl",
        [".t"] = "perl",
        [".psgi"] = "perl",
        [".p6"] = "perl6",
        [".pl6"] = "perl6",
        [".pm6"] = "perl6",
        [".nqp"] = "perl6",
        [".php"] = "php",
        [".php4"] = "php",
        [".php5"] = "php",
        [".phtml"] = "php",
        [".ctp"] = "php",
        [".ps1"] = "powershell",
        [".psm1"] = "powershell",
        [".psd1"] = "powershell",
        [".pssc"] = "powershell",
        [".psrc"] = "powershell",
        [".pug"] = "jade",
        [".jade"] = "jade",
        [".py"] = "python",
        [".rpy"] = "python",
        [".pyw"] = "python",
        [".cpy"] = "python",
        [".gyp"] = "python",
        [".gypi"] = "python",
        [".pyi"] = "python",
        [".ipy"] = "python",
        [".pyt"] = "python",
        [".r"] = "r",
        [".rhistory"] = "r",
        [".rprofile"] = "r",
        [".rt"] = "r",
        [".cshtml"] = "razor",
        [".razor"] = "razor",
        [".rb"] = "ruby",
        [".rbx"] = "ruby",
        [".rjs"] = "ruby",
        [".gemspec"] = "ruby",
        [".rake"] = "ruby",
        [".ru"] = "ruby",
        [".erb"] = "ruby",
        [".podspec"] = "ruby",
        [".rbi"] = "ruby",
        [".rs"] = "rust",
        [".scss"] = "scss",
        [".shader"] = "shaderlab",
        [".sh"] = "shellscript",
        [".bash"] = "shellscript",
        [".bashrc"] = "shellscript",
        [".bash_aliases"] = "shellscript",
        [".bash_profile"] = "shellscript",
        [".bash_login"] = "shellscript",
        [".bash_logout"] = "shellscript",
        [".ebuild"] = "shellscript",
        [".profile"] = "shellscript",
        [".xprofile"] = "shellscript",
        [".xsession"] = "shellscript",
        [".xsessionrc"] = "shellscript",
        [".zsh"] = "shellscript",
        [".zshrc"] = "shellscript",
        [".zprofile"] = "shellscript",
        [".zlogin"] = "shellscript",
        [".zlogout"] = "shellscript",
        [".zshenv"] = "shellscript",
        [".zsh-theme"] = "shellscript",
        [".ksh"] = "shellscript",
        [".csh"] = "shellscript",
        [".cshrc"] = "shellscript",
        [".tcshrc"] = "shellscript",
        [".yashrc"] = "shellscript",
        [".yash_profile"] = "shellscript",
        [".envrc"] = "shellscript",
        [".hushlogin"] = "shellscript",
        [".sql"] = "sql",
        [".dsql"] = "sql",
        // Svelte isn't a TextMateSharp-bundled grammar; BundledGrammarRegistryOptions ships it.
        [".svelte"] = "svelte",
        [".swift"] = "swift",
        [".ts"] = "typescript",
        [".tsx"] = "typescriptreact",
        [".typ"] = "typst",
        [".typc"] = "typst-code",
        [".vb"] = "vb",
        [".brs"] = "vb",
        [".vbs"] = "vb",
        [".bas"] = "vb",
        // .mod is deliberately absent from the xml block: it would claim go.mod.
        [".xml"] = "xml",
        [".xsd"] = "xml",
        [".ascx"] = "xml",
        [".atom"] = "xml",
        [".axml"] = "xml",
        [".axaml"] = "xml",
        [".bpmn"] = "xml",
        [".cpt"] = "xml",
        [".csl"] = "xml",
        [".csproj"] = "xml",
        [".dita"] = "xml",
        [".ditamap"] = "xml",
        [".dtd"] = "xml",
        [".ent"] = "xml",
        [".dtml"] = "xml",
        [".fsproj"] = "xml",
        [".fxml"] = "xml",
        [".iml"] = "xml",
        [".isml"] = "xml",
        [".jmx"] = "xml",
        [".launch"] = "xml",
        [".menu"] = "xml",
        [".mxml"] = "xml",
        [".nuspec"] = "xml",
        [".opml"] = "xml",
        [".owl"] = "xml",
        [".proj"] = "xml",
        [".props"] = "xml",
        [".pt"] = "xml",
        [".publishsettings"] = "xml",
        [".pubxml"] = "xml",
        [".rbxlx"] = "xml",
        [".rbxmx"] = "xml",
        [".rdf"] = "xml",
        [".rng"] = "xml",
        [".rss"] = "xml",
        [".shproj"] = "xml",
        [".storyboard"] = "xml",
        [".svg"] = "xml",
        [".targets"] = "xml",
        [".tld"] = "xml",
        [".tmx"] = "xml",
        [".vbproj"] = "xml",
        [".vcxproj"] = "xml",
        [".wsdl"] = "xml",
        [".wxi"] = "xml",
        [".wxl"] = "xml",
        [".wxs"] = "xml",
        [".xaml"] = "xml",
        [".xbl"] = "xml",
        [".xib"] = "xml",
        [".xlf"] = "xml",
        [".xliff"] = "xml",
        [".xpdl"] = "xml",
        [".xul"] = "xml",
        [".xoml"] = "xml",
        [".xsl"] = "xsl",
        [".xslt"] = "xsl",
        [".yml"] = "yaml",
        [".yaml"] = "yaml",
        [".eyaml"] = "yaml",
        [".eyml"] = "yaml",
    };

    // Exact filename → language id, for files identified by name rather than extension
    // (checked before the extension table so "tsconfig.json" wins over ".json"). Same
    // case-insensitive rationale as above, which also collapses Makefile/makefile.
    private static readonly Dictionary<string, string> ByFileName = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Dockerfile"] = "dockerfile",
        ["Containerfile"] = "dockerfile",
        ["Makefile"] = "makefile",
        ["GNUmakefile"] = "makefile",
        ["OCamlMakefile"] = "makefile",
        ["Jenkinsfile"] = "groovy",
        ["Jakefile"] = "javascript",
        ["composer.lock"] = "json",
        [".watchmanconfig"] = "json",
        ["tsconfig.json"] = "jsonc",
        ["jsconfig.json"] = "jsonc",
        ["babel.config.json"] = "jsonc",
        [".babelrc.json"] = "jsonc",
        [".ember-cli"] = "jsonc",
        ["gitconfig"] = "properties",
        ["Snakefile"] = "python",
        ["SConstruct"] = "python",
        ["SConscript"] = "python",
        ["Rakefile"] = "ruby",
        ["Gemfile"] = "ruby",
        ["Guardfile"] = "ruby",
        ["Podfile"] = "ruby",
        ["Capfile"] = "ruby",
        ["Cheffile"] = "ruby",
        ["Hobofile"] = "ruby",
        ["Vagrantfile"] = "ruby",
        ["Appraisals"] = "ruby",
        ["Rantfile"] = "ruby",
        ["Berksfile"] = "ruby",
        ["Berksfile.lock"] = "ruby",
        ["Thorfile"] = "ruby",
        ["Puppetfile"] = "ruby",
        ["Dangerfile"] = "ruby",
        ["Brewfile"] = "ruby",
        ["Fastfile"] = "ruby",
        ["Appfile"] = "ruby",
        ["Deliverfile"] = "ruby",
        ["Matchfile"] = "ruby",
        ["Scanfile"] = "ruby",
        ["Snapfile"] = "ruby",
        ["Gymfile"] = "ruby",
        ["APKBUILD"] = "shellscript",
        ["PKGBUILD"] = "shellscript",
        ["zshrc"] = "shellscript",
        ["zshenv"] = "shellscript",
        ["zlogin"] = "shellscript",
        ["zprofile"] = "shellscript",
        ["zlogout"] = "shellscript",
        ["bashrc_Apple_Terminal"] = "shellscript",
        ["zshrc_Apple_Terminal"] = "shellscript",
    };

    public static string? DetectLanguageId(string path)
    {
        if (string.IsNullOrEmpty(path)) return null;
        var fileName = Path.GetFileName(path);
        if (ByFileName.TryGetValue(fileName, out var byName)) return byName;
        var ext = Path.GetExtension(fileName);
        if (string.IsNullOrEmpty(ext)) return null;
        return ByExtension.TryGetValue(ext, out var id) ? id : null;
    }

    /// <summary>Every language id the registry can return, for tests that prove each one
    /// resolves to a loadable grammar.</summary>
    public static IEnumerable<string> AllLanguageIds
        => ByExtension.Values.Concat(ByFileName.Values).Distinct();
}
